'use client';
import {useState} from 'react';
const qualities=[['best','En yüksek kalite'],['1440','1440p · 2K'],['1080','1080p · Full HD'],['720','720p · HD'],['480','480p'],['360','360p'],['audio','Sadece ses']];
export default function Home(){
 const [url,setUrl]=useState(''); const [quality,setQuality]=useState('1440'); const [info,setInfo]=useState(null); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [progress,setProgress]=useState(0);
 async function inspect(){setError('');setInfo(null);if(!url.trim())return setError('Önce video bağlantısını girin.');setBusy(true);try{const r=await fetch('/api/info',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url})});const d=await r.json();if(!r.ok)throw new Error(d.error||'Video bilgisi alınamadı.');setInfo(d);}catch(e){setError(e.message)}finally{setBusy(false)}}
 async function download(){setError('');setBusy(true);setProgress(0);try{const r=await fetch('/api/download',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({url,quality})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||'İndirme başlatılamadı.')}const blob=await r.blob();const cd=r.headers.get('content-disposition')||'';const m=cd.match(/filename="?([^";]+)"?/i);const name=m?m[1]:'video.mp4';const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setProgress(100)}catch(e){setError(e.message)}finally{setBusy(false)}}
 return <main><div className="shell"><div className="brand"><span>▶</span><div><b>Video İndirici</b><small>PC · Mobil · 2K</small></div></div><section className="hero"><div className="badge">MP4 • 1440p / 2K</div><h1>Videonu seç,<br/><em>kaliteyi sen belirle.</em></h1><p>Yetkili olduğun içerikleri mobil veya bilgisayardan kolayca MP4 olarak indir.</p></section><section className="card"><label>Video bağlantısı</label><div className="urlrow"><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="YouTube video bağlantısını yapıştır…" inputMode="url"/><button className="secondary" onClick={inspect} disabled={busy}>{busy?'Kontrol…':'Kontrol Et'}</button></div><div className="controls"><div><label>Kalite</label><select value={quality} onChange={e=>setQuality(e.target.value)}>{qualities.map(([v,t])=><option key={v} value={v}>{t}</option>)}</select></div><button className="primary" onClick={download} disabled={busy||!url.trim()}>{busy?'Hazırlanıyor…':'Videoyu İndir ↓'}</button></div>{info&&<div className="info"><img src={info.thumbnail} alt=""/><div><strong>{info.title}</strong><span>{info.duration||''}{info.has1440?' · 1440p mevcut':''}</span></div></div>}{busy&&<div className="progress"><div style={{width:`${progress||8}%`}}/></div>}{error&&<div className="error">{error}</div>}<p className="note">Bu araç yalnızca indirme hakkınız bulunan içerikler için kullanılmalıdır.</p></section><footer>Video İndirici · Mobil ve masaüstü uyumlu</footer></div></main>
}
